apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app.kubernetes.io/name: retail
    app.kubernetes.io/component: api
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  HUGGINGFACE_API_KEY: {{ .Values.secrets.HUGGINGFACE_API_KEY | quote }}
